# E_mart/app/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import (
    UserViewSet,
    CategoryViewSet,
    ProductViewSet,
    OrderViewSet,
    OrderItemViewSet,
    WishlistViewSet
)

# Create a router and register your viewsets with it.
router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'order-items', OrderItemViewSet)
router.register(r'wishlist', WishlistViewSet)

urlpatterns = [
    # Your existing app URLs (if any) can go here, for example:
    # path('', views.home_view, name='home'),

    # Include the API URLs generated by the router under a 'v1/' prefix
    path('v1/', include(router.urls)),
    # Optional: Include DRF's browsable API login/logout views for development
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]
